import { Contract, Personnel, ChangeRequest } from './types';

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: 'C001',
    name: '国网福建信通公司2025年数字化运营保障合同',
    code: 'SGJXT00ZDJS25000216',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '026',
    amount: 185.78,
    taxRate: 2,
    status: '已完成',
    year: '2025'
  },
  {
    id: 'C002',
    name: '国网福建信通2025年核心业务系统运维合同',
    code: 'SGJXT00ZDJS25000510',
    type: '系统运营',
    partyB: '厦门华亿云图科技有限公司',
    purchaseOrder: '050',
    amount: 181.5,
    taxRate: 2,
    status: '已完成',
    year: '2025'
  },
  {
    id: 'C003',
    name: '国网福建信通公司2025年网络安全技术支持合同',
    code: 'SGJXT00ZDJS25000418',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '048',
    amount: 161.76,
    taxRate: 2,
    status: '已完成',
    year: '2025'
  },
  {
    id: 'C004',
    name: '基于电网资源业务数字化建设与支撑合同',
    code: 'SGJXT00ZDJS24000308',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '048',
    amount: 178.2,
    taxRate: 2,
    status: '已完成',
    year: '2024'
  },
  {
    id: 'C005',
    name: '国网福建信通2024年云平台支撑及数据治理合同',
    code: 'SGJXT00ZDJS24000106',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '046',
    amount: 128.352,
    taxRate: 2,
    status: '已完成',
    year: '2024'
  },
  {
    id: 'C006',
    name: '国网福建信通2024年SG186系统平台升级服务合同',
    code: 'SGJXT00ZDJS24000115',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '046',
    amount: 319.4,
    taxRate: 2,
    status: '常规运行',
    year: '2024'
  },
  {
    id: 'C007',
    name: '国网福建信通2024年数据中台运维与保障合同',
    code: 'SGJXT00ZDJS24000105',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '045',
    amount: 136.972,
    taxRate: 2,
    status: '已完成',
    year: '2024'
  },
  {
    id: 'C008',
    name: '国网福建信通2024年配网数字底座建设合同',
    code: 'SGJXT00ZDJS24000103',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '043',
    amount: 178.776,
    taxRate: 2,
    status: '已完成',
    year: '2024'
  },
  {
    id: 'C009',
    name: '国网福建信通2024年智慧供应链运营保障服务',
    code: 'SGJXT00ZDJS24000102',
    type: '系统运营',
    partyB: '厦门亿力吉奥信息科技有限公司',
    purchaseOrder: '042',
    amount: 240.75,
    taxRate: 2,
    status: '常规运行',
    year: '2024'
  },
  {
    id: 'C010',
    name: '国网福建信通2024年企业中台及微服务运行支撑',
    code: 'SGJXT00ZDJS24000101',
    type: '系统运营',
    partyB: '厦门华亿云图科技有限公司',
    purchaseOrder: '041',
    amount: 254.6,
    taxRate: 2,
    status: '常规运行',
    year: '2024'
  }
];

// Existing personnel mapped to contracts using contractId
export const INITIAL_PERSONNEL: Record<string, Personnel[]> = {
  'C001': [
    {
      id: 'P001',
      name: '李涛',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '专业分包人员',
      phone: '17759000077',
      idCard: '612522198507022637',
      education: '大学本科',
      title: '工程师',
      skillLevel: '高级工',
      joinWorkDate: '2016-07-01',
      coreTrade: '大数据运维工',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-08-27',
      status: '在职',
      terminalAddress: '10.135.24.89',
      attendanceLocation: '福州信通大楼B区4楼',
      station: 'W-405-A',
      otherInfo: '负责日常核心数据提取'
    },
    {
      id: 'P002',
      name: '张宇博',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '劳务分包人员',
      phone: '13950012234',
      idCard: '350102199011123412',
      education: '专科',
      title: '助理工程师',
      skillLevel: '中级工',
      joinWorkDate: '2018-03-12',
      coreTrade: '信息系统运维工',
      isOM: '否',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-08-27',
      status: '在职'
    },
    {
      id: 'P008',
      name: '刘明明',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '专业分包人员',
      phone: '13800138000',
      idCard: '35010219850101123X',
      education: '本科',
      title: '工程师',
      skillLevel: '中级工',
      joinWorkDate: '2019-01-01',
      coreTrade: '前端开发',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-01-01',
      status: '在职'
    },
    {
      id: 'P009',
      name: '陈建平',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '劳务分包人员',
      phone: '13511112222',
      idCard: '350102199005085555',
      education: '大专',
      title: '助理工程师',
      skillLevel: '初级工',
      joinWorkDate: '2020-05-01',
      coreTrade: '测试',
      isOM: '否',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-02-15',
      status: '在职'
    },
    {
      id: 'P010',
      name: '林美丽',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '专业分包人员',
      phone: '13922223333',
      idCard: '350102199208088888',
      education: '硕士',
      title: '高级工程师',
      skillLevel: '高级工',
      joinWorkDate: '2015-08-01',
      coreTrade: '后端开发',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-03-10',
      status: '在职'
    },
    {
      id: 'P011',
      name: '王小二',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '劳务分包人员',
      phone: '18888889999',
      idCard: '350102199801019999',
      education: '大专',
      title: '技术员',
      skillLevel: '初级工',
      joinWorkDate: '2022-01-01',
      coreTrade: '实施工程',
      isOM: '否',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-04-20',
      status: '在职'
    },
    {
      id: 'P012',
      name: '刘明明',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '运维保障人员',
      phone: '18677778888',
      idCard: '350102199505051234',
      education: '大专',
      title: '工程师',
      skillLevel: '中级工',
      joinWorkDate: '2020-03-01',
      coreTrade: '系统测试',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-04-20',
      status: '在职',
      terminalAddress: '10.135.24.116',
      attendanceLocation: '福州国网信通科技楼A栋',
      station: 'Desk #O-0428-B'
    },
    {
      id: 'P013',
      name: '黄志雄',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '专业分包人员',
      phone: '13955556666',
      idCard: '350102199001018888',
      education: '本科',
      title: '高级工程师',
      skillLevel: '高级工',
      joinWorkDate: '2015-07-01',
      coreTrade: '架构师',
      isOM: '否',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-04-20',
      status: '在职'
    },
    {
      id: 'P014',
      name: '吴强',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '运维保障人员',
      phone: '13599990000',
      idCard: '350102198808085555',
      education: '本科',
      title: '工程师',
      skillLevel: '中级工',
      joinWorkDate: '2016-01-01',
      coreTrade: '数据库管理',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-04-20',
      status: '在职',
      terminalAddress: '10.135.24.118',
      attendanceLocation: '厦门路路通综合运营大厅',
      station: 'Desk #O-0501-A'
    }
  ],
  'C002': [
    {
      id: 'P003',
      name: '洪晓华',
      companyName: '厦门华亿云图科技有限公司',
      personnelType: '高级咨询顾问',
      phone: '18965123388',
      idCard: '350203198804251234',
      education: '硕士研究生',
      title: '高级工程师',
      skillLevel: '技师',
      joinWorkDate: '2011-09-01',
      coreTrade: '架构设计师',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-09-02',
      status: '在职',
      terminalAddress: '10.135.32.110',
      attendanceLocation: '厦门思明研发中心8楼',
      station: 'X-801',
      otherInfo: '架构优化设计及升级支撑'
    }
  ],
  'C003': [
    {
      id: 'P004',
      name: '王少杰',
      companyName: '厦门亿力吉奥信息科技有限公司',
      personnelType: '专业技术人员',
      phone: '15060012356',
      idCard: '350122199510123045',
      education: '大学本科',
      title: '工程师',
      skillLevel: '高级工',
      joinWorkDate: '2017-06-15',
      coreTrade: '网络安全守卫工',
      isOM: '是',
      businessResult: '通过',
      safetyResult: '通过',
      certResult: '适配',
      confidentialitySigned: true,
      confidentialityDate: '2025-08-29',
      status: '在职',
      terminalAddress: '10.135.112.56',
      attendanceLocation: '福州信通大楼A区红队实验室',
      station: 'R-132',
      otherInfo: '负责渗透测试与安规排查'
    }
  ]
};

export const INITIAL_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'CR001',
    contractId: 'C001',
    contractName: '国网福建信通公司2025年数字化运营保障合同',
    requestDescription: '新增驻场运维工程师',
    requestDate: '2026-06-05',
    entryMaterials: '个人简历与资质证书.pdf',
    addedPersonnel: [
      {
        id: 'P005',
        name: '赵子杰',
        companyName: '厦门亿力吉奥信息科技有限公司',
        personnelType: '专业分包人员',
        phone: '13860129202',
        idCard: '350521199302142231',
        education: '大学本科',
        title: '助理工程师',
        skillLevel: '中级工',
        joinWorkDate: '2019-07-10',
        coreTrade: '系统数据库运维工',
        isOM: '是',
        businessResult: '通过',
        safetyResult: '通过',
        certResult: '适配',
        confidentialitySigned: true,
        confidentialityDate: '2026-06-05',
        status: '待审核' // status represents pending approval state
      },
      {
        id: 'P006',
        name: '周清清',
        companyName: '厦门亿力吉奥信息科技有限公司',
        personnelType: '运维保障人员',
        phone: '15280034411',
        idCard: '35010319960528412X',
        education: '大学本科',
        title: '无',
        skillLevel: '中级工',
        joinWorkDate: '2021-03-15',
        coreTrade: '机房运维工',
        isOM: '否',
        businessResult: '通过',
        safetyResult: '通过',
        certResult: '适配',
        confidentialitySigned: true,
        confidentialityDate: '2026-06-05',
        status: '待审核'
      }
    ],
    removedPersonnel: [
      {
        id: 'P901',
        name: '张三撤',
        companyName: '厦门亿力吉奥信息科技有限公司',
        personnelType: '专业分包人员',
        phone: '13912345678',
        idCard: '350102199001014321',
        education: '大学本科',
        title: '助理工程师',
        skillLevel: '中级工',
        joinWorkDate: '2020-05-01',
        coreTrade: '前端开发',
        isOM: '否',
        businessResult: '通过',
        safetyResult: '通过',
        certResult: '适配',
        status: '已退场',
      confidentialitySigned: false
    },
      {
        id: 'P902',
        name: '李四退',
        companyName: '厦门亿力吉奥信息科技有限公司',
        personnelType: '运维保障人员',
        phone: '13887654321',
        idCard: '350102199202021234',
        education: '专科',
        title: '无',
        skillLevel: '初级工',
        joinWorkDate: '2021-08-01',
        coreTrade: '系统测试',
        isOM: '是',
        businessResult: '通过',
        safetyResult: '通过',
        certResult: '适配',
        status: '已退场',
      confidentialitySigned: false
    }
    ],
    status: '待数字化部审批',
    approverOpinion: ''
  },
  {
    id: 'CR002',
    contractId: 'C003',
    contractName: '国网福建信通公司2025年网络安全技术支持合同',
    requestDescription: '网络安全技术支持人员进场',
    requestDate: '2026-06-02',
    entryMaterials: '资质适配及体检报告.zip',
    addedPersonnel: [
      {
        id: 'P007',
        name: '林建国',
        companyName: '厦门亿力吉奥信息科技有限公司',
        personnelType: '现场运维人员',
        phone: '13612345678',
        idCard: '350204198902042139',
        education: '专科',
        title: '工程师',
        skillLevel: '高级工',
        joinWorkDate: '2013-05-01',
        coreTrade: '电力电缆工',
        isOM: '是',
        businessResult: '通过',
        safetyResult: '通过',
        certResult: '适配',
        confidentialitySigned: true,
        confidentialityDate: '2026-06-02',
        status: '待审核'
      }
    ],
    removedPersonnel: [],
    status: '待专责归档', // Approved by Department Head, but waiting for Dedicated Specialist (专责) to set O&M details
    approverOpinion: '资质合规，同意该人员进场部署。',
    approverName: '刘部长',
    approvalDate: '2026-06-03'
  }
];
